### ISSUE TITLE
Permission to use as a base game engine?

### ISSUE THREAD

**Issue by ghost** [TheRealMJP/BakingLab#3]
Hi, I realize this is under the MIT license, but I would consider it rude of myself not to contact you and let you know that I wish to use this as the base of a beginner's game engine? Your code makes it so much easier for me to understand how things work. It would be used in a free game.

Also: I noticed that the SampleFramework version seems to change from project to project. Which version is the "best"? I notice that not all versions come with a version number, so I'm slightly confused.

Thank you for your time.

**Comment by TheRealMJP** [comment]
Hey there,

Please feel free to use whatever code you would like, I don't mind one bit! I would be happy to answer any questions too if you have any, or need some advice about your own engine.

On my earlier samples I would always fork the sample framework for each sample, which ended up getting hard to maintain. So at some point I started sharing the sample framework code among the samples in my private repo, and using a versioning scheme for whenever I decided to make breaking changes. BakingLab is using the last version that I made for the D3D11 version of my sample framework (v1.02), so you can consider the code in this repo to be the latest in terms of the D3D11 version. These days I mainly work with the D3D12 version of my framework, which also has a some changes that aren't related to the graphics API. The sample framework in the [DeferredTexturing repo](https://github.com/TheRealMJP/DeferredTexturing) is pretty much up-to-date with what I have in my private repo, so you can look at that if you're curious. One big change in particular that I made for the D3D12 version is that I switched to using [Dear Imgui](https://github.com/ocornut/imgui) for my UI, which is generally much nicer and more flexible than what I used in the D3D11 framework ([AntTweakBar](http://anttweakbar.sourceforge.net/)). 

Good luck!

-Matt

**Comment by ghost** [comment]
Thanks, you're awesome :)

I suppose I do have an hlsl related question, though it's minor. I often see in various shaders people define something a float more than once (such as "float shadow = 1.0f"), is this correct? I would think you could just do "float shadow = 1.0" right?

**Comment by TheRealMJP** [comment]
Yes, that's right: in HLSL "1.0" and "1.0f" are equivalent, and both have the type "float". I mostly add the "f" out of habit from working in C/C++, where "1.0f" is a float, and "1.0" is a double (in HLSL you need to use "1.0L" if you want double-precision). There's some more info here: [https://msdn.microsoft.com/en-us/library/windows/desktop/bb509567(v=vs.85).aspx](https://msdn.microsoft.com/en-us/library/windows/desktop/bb509567(v=vs.85).aspx)

**Comment by ghost** [comment]
Ok, that makes sense. Also, looks like I've been doing doubles wrong this whole time XD  My only excuse is that I'm a pothead, so I'll blame that, lol.

Anyway, thanks again. I'll close this issue for you so it doesn't keep popping up.
