### ISSUE TITLE
I have a question. I request you to help.

### ISSUE THREAD

**Issue by oschakravarthi** [TheRealMJP/BakingLab#9]
Dear Guru(s),

Thank you very much for the great effort. 

I have a question. I request you to help. Sorry for asking my question as a "issue". I could not find any option in github to post a message to you.

I have been looking for a library which generates shadow map images (Image Based Lighting) for each mesh of my scene. (2nd UV channel). I mean,  when we bake lighting of a scene in 3D editors like Blender/Maya/3ds max, it generates lightmap images which contain shadow information. I want to generate the same images programatically without using any such 3d editors. I have attached a a sample image to this post. 
![9551170d15e201dad1c45266079ec43f8eaade55](https://user-images.githubusercontent.com/29388049/56782484-f7ea5c00-6804-11e9-9a21-c51c4db4682c.jpeg)

Is it possible to achieve the same with BakingLab? If not possible, do you know any such library which is free/opensource?

I have seen many Path-Tracing/Ray-Tracing libraries but they all are rendering the complete scene without giving a clue how to generate those images. I have been struggling for more than 2 months.

I have a request too.
It will be great if BakingLab is split into two parts - Core and UI so that the core library can be used in any other application.

Awaiting your reply.
Thanks in advance.

**Comment by TheRealMJP** [comment]
Hey there,

BakingLab is really just for educational use, or experimentation. It would need all kinds of work to be useful as a tool for baking lightmaps, and to be perfectly honest I have no interest in doing that work or maintaining such a tool. I'm also not aware of any free or open source libraries that could achieve this for you.
